version: '3'

services: 

  mongodb:
    image: mongo:latest
    container_name: "cz-mongodb"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cz-password